spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

      